Q1. Understanding Feature Distributions (Iris Dataset)

Context: Before training any ML model, we analyze feature distributions.

Dataset: Load Iris dataset from sklearn

Tasks:

1. Extract feature matrix as NumPy array
2. Compute:
Mean
Median
Standard deviation
Variance (for each feature)
3. Identify:
Which feature has highest variability and why it matters in ML
4. Convert any one feature into shape (n,1) and explain why ML models expect this format

In [1]:
import seaborn as sns
import pandas as pd
import numpy as np

In [2]:
from sklearn.datasets import load_iris
import numpy as np
iris=load_iris()
#q1
data=iris.data

#q2
mean=np.mean(data,axis=0)
median= np.median(data,axis=0)
std_dev= np.std(data,axis=0)
var=np.var(data,axis=0)
print('Feature-wise mean:',mean)
print('Feature-wise median:',median)
print('Feature-wise standard deviation:',std_dev)
print('Feature-wise variance:',var)

# q3)
print('Feature index 2 (3rd feature) has highest variability',var[2])
# A feature with more spread can:better separate data points
# help model learn patterns

# q4)

reshape_feature=data[:,2].reshape(-1,1)
print(reshape_feature.shape)
data

Feature-wise mean: [5.84333333 3.05733333 3.758      1.19933333]
Feature-wise median: [5.8  3.   4.35 1.3 ]
Feature-wise standard deviation: [0.82530129 0.43441097 1.75940407 0.75969263]
Feature-wise variance: [0.68112222 0.18871289 3.09550267 0.57713289]
Feature index 2 (3rd feature) has highest variability 3.0955026666666674
(150, 1)

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

Q2. Data Selection for Model Input

Context: Models are trained on selective features, not full raw data.

Dataset: Iris

Tasks:

1. Extract:
First 100 samples
Only last 2 features
2. Use boolean masking:
Select samples where petal length is greater than dataset mean
3. Count selected samples
4. Explain how this relates to feature-based filtering in ML

In [3]:
iris=load_iris()
dataa=iris.data
print(iris.feature_names)
data100=dataa[0:100]
last_two_features=data100[:, -2:]
print(last_two_features)
petal_length = dataa[:, 2]
mean_p=np.mean(petal_length)
mask = petal_length > mean_p
filtered_data = dataa[mask]

print(filtered_data)
print("Count:", len(filtered_data))

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[[1.4 0.2]
 [1.4 0.2]
 [1.3 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [1.7 0.4]
 [1.4 0.3]
 [1.5 0.2]
 [1.4 0.2]
 [1.5 0.1]
 [1.5 0.2]
 [1.6 0.2]
 [1.4 0.1]
 [1.1 0.1]
 [1.2 0.2]
 [1.5 0.4]
 [1.3 0.4]
 [1.4 0.3]
 [1.7 0.3]
 [1.5 0.3]
 [1.7 0.2]
 [1.5 0.4]
 [1.  0.2]
 [1.7 0.5]
 [1.9 0.2]
 [1.6 0.2]
 [1.6 0.4]
 [1.5 0.2]
 [1.4 0.2]
 [1.6 0.2]
 [1.6 0.2]
 [1.5 0.4]
 [1.5 0.1]
 [1.4 0.2]
 [1.5 0.2]
 [1.2 0.2]
 [1.3 0.2]
 [1.4 0.1]
 [1.3 0.2]
 [1.5 0.2]
 [1.3 0.3]
 [1.3 0.3]
 [1.3 0.2]
 [1.6 0.6]
 [1.9 0.4]
 [1.4 0.3]
 [1.6 0.2]
 [1.4 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [4.7 1.4]
 [4.5 1.5]
 [4.9 1.5]
 [4.  1.3]
 [4.6 1.5]
 [4.5 1.3]
 [4.7 1.6]
 [3.3 1. ]
 [4.6 1.3]
 [3.9 1.4]
 [3.5 1. ]
 [4.2 1.5]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]
 [4.4 1.4]
 [4.5 1.5]
 [4.1 1. ]
 [4.5 1.5]
 [3.9 1.1]
 [4.8 1.8]
 [4.  1.3]
 [4.9 1.5]
 [4.7 1.2]
 [4.3 1.3]
 [4.4 1.4]
 [4.8 1.4]
 [5.  1.7]
 [4.5 1.5]
 [3.5 1. ]
 [3.8 1.1]
 [3.7 1. ]
 [3.9 1.2]
 [5.1 1.6]
 [4.5 1.5]
 [4.5 1.6]
 [4.7 1.5]
 [4.4 1.3]
 [4.1 1.3]
 [4.  1.3]
 [4.4 1.2]
 [4.6 1.4]
 [4.  1.2]
 [3.3 1. ]
 [4.2 1.3]
 [4.2 1.2]
 [4.2 1.3]
 [4.3 1.3]
 [3.  1.1]
 [4.1 1.3]]
[[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.5 2.4 3.8 1.1]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.5 4.  1.3]
 [5.5 2.6 4.4 1.2]
 [6.1 3.  4.6 1.4]
 [5.8 2.6 4.  1.2]
 [5.6 2.7 4.2 1.3]
 [5.7 3.  4.2 1.2]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [5.7 2.8 4.1 1.3]
 [6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]
 [7.6 3.  6.6 2.1]
 [4.9 2.5 4.5 1.7]
 [7.3 2.9 6.3 1.8]
 [6.7 2.5 5.8 1.8]
 [7.2 3.6 6.1 2.5]
 [6.5 3.2 5.1 2. ]
 [6.4 2.7 5.3 1.9]
 [6.8 3.  5.5 2.1]
 [5.7 2.5 5.  2. ]
 [5.8 2.8 5.1 2.4]
 [6.4 3.2 5.3 2.3]
 [6.5 3.  5.5 1.8]
 [7.7 3.8 6.7 2.2]
 [7.7 2.6 6.9 2.3]
 [6.  2.2 5.  1.5]
 [6.9 3.2 5.7 2.3]
 [5.6 2.8 4.9 2. ]
 [7.7 2.8 6.7 2. ]
 [6.3 2.7 4.9 1.8]
 [6.7 3.3 5.7 2.1]
 [7.2 3.2 6.  1.8]
 [6.2 2.8 4.8 1.8]
 [6.1 3.  4.9 1.8]
 [6.4 2.8 5.6 2.1]
 [7.2 3.  5.8 1.6]
 [7.4 2.8 6.1 1.9]
 [7.9 3.8 6.4 2. ]
 [6.4 2.8 5.6 2.2]
 [6.3 2.8 5.1 1.5]
 [6.1 2.6 5.6 1.4]
 [7.7 3.  6.1 2.3]
 [6.3 3.4 5.6 2.4]
 [6.4 3.1 5.5 1.8]
 [6.  3.  4.8 1.8]
 [6.9 3.1 5.4 2.1]
 [6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]
Count: 93

Q3. Feature Scaling using NumPy (Very Important)

Context: Most ML models require normalized data.

Dataset: Iris (NumPy array)

Tasks:

1. Apply standardization:

$$
X' = \frac{X - \mu}{\sigma}
$$
	​2. 

Verify:
Mean ≈ 0
Std ≈
on

In [4]:
iris2=load_iris()
data2=iris2.data
data2
fs_mean=np.mean(data2,axis=0)
fs_std=np.std(data2,axis=0)
scaled_data=(data2 - fs_mean) / fs_std
a=np.mean(scaled_data, axis=0)
b=np.std(scaled_data, axis=0)
print(a,'a')
print(b,'b')

[-1.69031455e-15 -1.84297022e-15 -1.69864123e-15 -1.40924309e-15] a
[1. 1. 1. 1.] b

Q4. Dataset Understanding (Titanic Dataset)

Context: First step in ML pipeline is dataset inspection.

Dataset: Titanic (Seaborn)

Tasks:

1. Display:
head(), tail()
info(), describe()
2. Identify:
Missing values per column
Numerical vs categorical features
3. Explain:
Why identifying feature types is important before modeling

In [5]:
import seaborn as sns
df = sns.load_dataset("titanic")
df.head()
df.tail()
df.info()
df.describe()
df.isnull().sum()

# Numerical features include age, fare, sibsp, etc., while categorical features include sex, embarked, class, etc.
# The deck column has the highest missing values, followed by age, while embarked and embark_town have very few missing values.
# Identifying feature types is important because numerical features require scaling,
# while categorical features require encoding before applying machine learning models.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

Q5. Filtering Data for Business Logic

Context: Real ML problems require filtering relevant populations.

Dataset: Titanic

Tasks:

1. Filter:
Female passengers in 1st class
2. Compute:
Survival rate for this group
3. Compare with overall survival rate
4. Interpret:
What insight can be used in ML feature engineering

In [6]:
df.head()
first_class_females=df[(df['sex'] == 'female') & (df['pclass'] == 1)]
mean_group=first_class_females['survived'].mean()
print(mean_group)
overall_mean=df['survived'].mean()
print(overall_mean)

if mean_group>overall_mean:
    print('First-class females have a higher survival rate than overall passengers')
else:
    print('Overall Survival rate is higher')

0.9680851063829787
0.3838383838383838
First-class females have a higher survival rate than overall passengers

Q6. Handling Missing Data (Critical ML Step)

Context: Models cannot handle null values.

Dataset: Titanic

Tasks:

1. Fill missing age using median
2. Fill missing embarked using mode
3. Drop deck column
4. Explain:
Why different strategies are used for different columns

In [7]:
df_dummy=df.copy()
df_dummy.head()
df_dummy.isnull().sum()
median_age=df_dummy['age'].median()
print(median_age)
mode_embarked=df_dummy['embark_town'].mode()[0]
print(mode_embarked)

df_dummy['age'].fillna(median_age, inplace=True)
df_dummy['embark_town'].fillna(mode_embarked,inplace=True)

df_dummy.isnull().sum()

28.0
Southampton

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5936\3341071588.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_dummy['age'].fillna(median_age, inplace=True)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5936\3341071588.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_dummy['embark_town'].fillna(mode_embarked,inplace=True)

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      0
alive            0
alone            0
dtype: int64

Q7. Feature Engineering for Model Improvement

Context: Raw data is rarely useful—features must be created.

Dataset: Titanic

Tasks:

1. Create:
family_size = sibsp + parch + 1
2. Create:
is_alone (binary feature)
3. Compute survival rate by is_alone
4. Explain:
Why engineered features improve ML models

In [8]:
df_copy=df.copy()
df_copy['family_size']= df_copy['sibsp'] + df_copy['parch'] + 1
df_copy['is_alone'] = (df_copy['family_size'] == 1).astype(int)

print((df_copy[['sibsp','parch','family_size','is_alone']].head()))

df_copy.groupby('is_alone')['survived'].agg(['mean'])

# Engineered features improve ML models because they capture meaningful patterns and relationships 
# that are not directly visible in raw data, making it easier for the model to learn and make accurate predictions.

   sibsp  parch  family_size  is_alone
0      1      0            2         0
1      1      0            2         0
2      0      0            1         1
3      1      0            2         0
4      0      0            1         1

              mean
is_alone
0         0.505650
1         0.303538

Q8. Group-Based Insights (Customer Segmentation Logic)

Context: ML models often depend on aggregated patterns.

Dataset: Tips

Tasks:

1. Compute:
Average tip by day
Total bill by gender
2. Create new feature:
tip_percentage
3. Identify:
Which day has highest tipping behavior
4. Explain:
How this helps in segmentation models

In [9]:
tips_df=sns.load_dataset('tips')
print(tips_df.groupby('sex')['total_bill'].agg(['sum']))
print()
print(tips_df.groupby('day')['tip'].agg(['mean']))
print()
tips_df['tip_percentage']=tips_df['tip']/tips_df['total_bill']
print()
print(tips_df.groupby('day')['tip_percentage'].mean().idxmax())
print()
print(tips_df.head())

# Aggregated features help identify behavioral patterns across groups, which is useful for segmenting customers and improving model predictions.

            sum
sex
Male    3256.82
Female  1570.95

          mean
day
Thur  2.771452
Fri   2.734737
Sat   2.993103
Sun   3.255132


Fri

   total_bill   tip     sex smoker  day    time  size  tip_percentage
0       16.99  1.01  Female     No  Sun  Dinner     2        0.059447
1       10.34  1.66    Male     No  Sun  Dinner     3        0.160542
2       21.01  3.50    Male     No  Sun  Dinner     3        0.166587
3       23.68  3.31    Male     No  Sun  Dinner     2        0.139780
4       24.59  3.61  Female     No  Sun  Dinner     4        0.146808

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5936\3402157708.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(tips_df.groupby('sex')['total_bill'].agg(['sum']))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5936\3402157708.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(tips_df.groupby('day')['tip'].agg(['mean']))
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5936\3402157708.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(tips_df.groupby('day')['tip_percentage'].mean().idxmax())

Q9. Advanced Filtering + Subsetting

Context: Training data is often filtered based on business rules.

Dataset: Tips

Tasks:

1. Filter:
total_bill > 20 AND tip < 3
2. Select only relevant columns
3. Analyze:
Is this segment under-tipping?
4. Explain:
How such filtering helps anomaly detection

In [10]:
tips_df=sns.load_dataset('tips')
total_bill_filter=tips_df[(tips_df['total_bill']>20) & (tips_df['tip']<3)]
relevant_bill_cols = total_bill_filter[['total_bill', 'tip']]
relevant_bill_cols

# Yes, this segment is under-tipping because customers with higher bills are giving relatively low tips.


# Such filtering helps identify unusual patterns (like high spending but low tipping), which can be considered anomalies. 
# These anomalies can be useful in machine learning for detecting outliers, fraud, or abnormal customer behavior.

     total_bill   tip
21        20.29  2.75
33        20.69  2.45
48        28.55  2.05
57        26.41  1.50
68        20.23  2.01
102       44.30  2.50
113       23.95  2.55
119       24.08  2.92
129       22.82  2.18
131       20.27  2.83
153       24.55  2.00
166       20.76  2.24
187       30.46  2.00
192       28.44  2.56
208       24.27  2.03
210       30.06  2.00
229       22.12  2.88
230       24.01  2.00
237       32.83  1.17
240       27.18  2.00
241       22.67  2.00

Q10. Data Transformation for Model Input (NumPy)

Context: ML models require structured numeric arrays.

Tasks:

1. Create two arrays of shape (3,2)
2. Perform:
Vertical stacking
Horizontal stacking
3. Reshape into (2,6)
4. Explain:
Why reshaping is required in ML pipelines

In [11]:
array1=np.random.rand(3,2)
array2=np.random.rand(3,2)

v_stack = np.vstack((array1, array2))
h_stack=np.hstack((array1,array2))

reshape2_6=h_stack.reshape(2,6)
reshape2_6

# Reshaping is required because machine learning models expect data in a specific format (usually 2D: samples × features). 
# It ensures data is structured correctly for model input.

array([[0.1957091 , 0.87728705, 0.01624854, 0.16276746, 0.51784099,
        0.2824087 ],
       [0.72698587, 0.62794143, 0.28077723, 0.46116544, 0.85932511,
        0.30422177]])

Q11. End-to-End ML Preprocessing Pipeline (Titanic)

Context: Prepare dataset for ML model training

Tasks:

1. Load dataset
2. Handle missing values
3. Encode categorical variables (sex, embarked)
4. Normalize numerical features
5. Convert to NumPy array

Output:

Final feature matrix ready for model training

In [12]:
from sklearn.preprocessing import StandardScaler
df11=sns.load_dataset('titanic')
df11.isnull().sum()
df11['age'] = df11['age'].fillna(df11['age'].median())
df11['embarked'] = df11['embarked'].fillna(df11['embarked'].mode()[0])
df11 = df11.drop(columns=['deck'])
df11 = pd.get_dummies(df11, columns=['sex', 'embarked'], drop_first=True)


X = df11.drop(columns=['survived'])
y = df11['survived']
X_np = np.array(X)
y_np = np.array(y)



scaler = StandardScaler()
X[['age', 'fare']] = scaler.fit_transform(X[['age', 'fare']])

# Final output
print("Feature matrix shape:", X_np.shape)
print("Target shape:", y_np.shape)

Feature matrix shape: (891, 14)
Target shape: (891,)

Q12. Feature Selection using Statistical Understanding

Context: Not all features improve model performance.

Dataset: Iris

Tasks:

1. Compute correlation matrix
2. Identify highly correlated features
3. Drop redundant features
4. Explain:
Impact on overfitting and model performance

In [13]:
iris12=load_iris()
data12=iris12.data
iris_df = pd.DataFrame(iris12.data, columns=iris.feature_names)
iris_df = iris_df.drop(columns=['petal width (cm)'])
iris_df.corr()
# The correlation matrix shows that petal length and petal width are highly correlated (0.96), indicating redundancy. 
# Removing one of these features helps reduce overfitting, simplifies the model, and improves performance.

                   sepal length (cm)  sepal width (cm)  petal length (cm)
sepal length (cm)           1.000000          -0.11757           0.871754
sepal width (cm)           -0.117570           1.00000          -0.428440
petal length (cm)           0.871754          -0.42844           1.000000

Q13. Custom Feature Transformation using apply()

Context: Real ML requires custom logic transformation.

Dataset: Titanic

Tasks:

1. Create age_group:
Child / Adult / Senior
2. Use .apply()
3. Compute survival rate per group
4. Interpret:
Which segment has highest survival likelihood

In [14]:
import seaborn as sns
import pandas as pd

df = sns.load_dataset('titanic')
df['age'] = df['age'].fillna(df['age'].median())

def age_group_func(age):
    if age < 18:
        return 'Child'
    elif age < 60:
        return 'Adult'
    else:
        return 'Senior'

df['age_group'] = df['age'].apply(age_group_func)

survival_by_group = df.groupby('age_group')['survived'].mean()
print(survival_by_group)
df

age_group
Adult     0.364362
Child     0.539823
Senior    0.269231
Name: survived, dtype: float64

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age_group
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,Adult
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,Adult
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,Adult
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,Adult
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,Adult
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,Adult
888,0,3,female,28.0,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,Adult
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,Adult
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,Adult

Q14. Error Analysis Simulation (Model Evaluation Thinking)

Context: Understanding prediction errors is key in ML.

Tasks:

1. Generate 1000 random error values using NumPy
2. Compute:
Mean
Standard deviation
3. Identify outliers:
Using mean ± 2*std
4. Explain:
What high variance means in model performance

In [15]:
import numpy as np
errors = np.random.randn(1000)   
mean_error = np.mean(errors)
std_error = np.std(errors)

print("Mean:", mean_error)
print("Std Dev:", std_error)
lower_bound = mean_error - 2 * std_error
upper_bound = mean_error + 2 * std_error

outliers = errors[(errors < lower_bound) | (errors > upper_bound)]
print("Number of outliers:", len(outliers))

Mean: -0.025828306308311674
Std Dev: 1.0172446871501213
Number of outliers: 44

Q15. Business + ML Insight Problem (Tips Dataset)

Context: Convert data analysis into decision-making

Tasks:

1. Create:
tip_percentage
2. Group by:
day and time
3. Identify:
Highest revenue segment
4. Provide:
Recommendation for business strategy
How ML model can use this insight

In [16]:
tips_df = sns.load_dataset('tips')
tips_df['tip_percentage']=tips_df['tip']/tips_df['total_bill']
grouped = tips_df.groupby(['day', 'time'])['total_bill'].sum()
print(grouped)
grouped.idxmax()

# The highest revenue is generated during Saturday dinner, indicating that this is the most profitable time segment for the business.
# Identifying high-revenue segments helps optimize business operations and improve predictive modeling.

day   time
Thur  Lunch     1077.55
      Dinner      18.78
Fri   Lunch       89.92
      Dinner     235.96
Sat   Lunch        0.00
      Dinner    1778.40
Sun   Lunch        0.00
      Dinner    1627.16
Name: total_bill, dtype: float64

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_5936\2148809464.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped = tips_df.groupby(['day', 'time'])['total_bill'].sum()

('Sat', 'Dinner')